### ISSUE TITLE
Update for 7.2

### ISSUE THREAD

**Issue by arecaps** [Swader/homestead_improved#21]
Can you update?

**Comment by Swader** [comment]
Done

**Comment by Taariqq** [comment]
How do I make nginx use php 7.3 instead of 7.0.x on all sites?
When I do php -v on command line I get php version 7.3.x
But when I run phpinfo() from one of my sites it says php 7.0.x

I see the solution of going into /etc/nginx/sites-enabled and going into every xyz.app and changing to php 7.3
... but, is there a way to make it permanent so that the web server uses php 7.3 by default?

**Comment by Swader** [comment]
Ah, yeah, the serve scripts need to be updated, the templates in the scripts folder. Once those are up to date, all future servers will use 7.3. I'll try and do that these days

**Comment by Taariqq** [comment]
> Ah, yeah, the serve scripts need to be updated, the templates in the scripts folder. Once those are up to date, all future servers will use 7.3. I'll try and do that these days

I found a way around it, by changing homestead.app to point to the right file. The good folks at SitePoint were very helpful.

Another question. Can you update it to use Homestead 8.4? Right now it uses 8.0.0 alpha.

Much appreciate it.

**Comment by Swader** [comment]
Sure I'll do that!
