### ISSUE TITLE
serve.sh script can not be located (again)

### ISSUE THREAD

**Issue by rutger1413** [Swader/homestead_improved#4]
I am having the same issue as #1 . There have been commits that fix the issue, but they have subsequently been reverted. I am on OSX 10.10 and having the fixes from #1 in made it work for me. Without those fixes, I get the same error.

**Comment by Swader** [comment]
I'm looking into this. My own copy started breaking badly when I applied the fix, and some others reported the same. Thus a revert was made.

I am considering abandoning this fork, because the original homestead has now implemented everything I improved upon it - in response to this, they even made it possible to boot up again without having PHP installed locally, so this really has very little reason to exist any more.

**Comment by rutger1413** [comment]
I still prefer homestead improved for the simple need  to setup ssh keys. Not a big deal, but when all my other vagrant boxes I just vagrant ssh and I am in. I prefer consistency :)

Regardless, thanks for the effort.
