### ISSUE TITLE
How to create an Apache version?

### ISSUE THREAD

**Issue by gandalf458** [Swader/homestead_improved#8]
Is it possible to create a version of this using Apache rather than Nginx? I don't see where the packages included are specified...

**Comment by Swader** [comment]
There is no Apache installed - this is a fixed setup of LEMP. You can, however, easily manually install Apache instead of Nginx once you SSH into the VM.

If you're not comfortable doing that, I encourage you to use a GUI tool for customizing Vagrant VMs like [Puphpet](https://www.sitepoint.com/build-virtual-machines-easily-puphpet/), Phansible, and [others](https://www.sitepoint.com/5-easy-ways-getting-started-php-vagrant/).
